name: Build and Deploy
on:
  push:
    branches:
      - 1-feature-monthly-blog
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Setup Ruby, JRuby and TruffleRuby
        uses: ruby/setup-ruby@v1.47.0
        with:
          ruby-version: 2.6.6 # Not needed with a .ruby-version file
#          bundler-cache: true

      - run:  bundle install
#      - run:  bundle exec rake

      - name: Install and Build ğŸ”§ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run gh-deploy-prod

      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: false # Automatically remove deleted files from the deploy branch
